name: CI to update tags with changes 
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install docs dependencies
        run: pip install -r requirements.txt 
      - name: Fetch GH-PAGES
        run: git fetch origin gh-pages --depth=1
      - name: Setup Git User
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Update the latest doc version
        run:  mike deploy ${{ steps.get_version.outputs.VERSION }} -b gh-pages --push

