name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install dependencies
        run: pip install mkdocs-material 
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - name: Publish new doc version
        run:  mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest
      - name: Change default latest version
        run:  mike set-default --push latest
      # - run: mkdocs gh-deploy --force


